package net.tenie.Sqlucky.sdk.po;

/*   @author tenie */
public enum TreeItemType {
	ROOT, CONNECT_INFO,  SCHEMA_ROOT, SCHEMA, TABLE_ROOT, TABLE, VIEW_ROOT, VIEW, FUNCTION_ROOT, FUNCTION, 
	PROCEDURE_ROOT,  PROCEDURE,
	INDEX_ROOT,  INDEX,
	SEQUENCE_ROOT,  SEQUENCE,
	TRIGGER_ROOT,  TRIGGER
	;

}
